name: Deploy front
 
on:
  push:
    branches:
      - master
    paths:
      - 'front/src/**'
    tags:
      - deploy_front*
 
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    defaults:
      run:
        working-directory: ./front
    env:
      TEAMS_URL: ${{ secrets.TEAMS_URL }}
      ACCESS_TOKEN:  ${{ secrets.FRONT_ACCESS_TOKEN_MASTER }}
      GITHUB_USERNAME:  btctc-coordinate 
    steps:
    - uses: actions/checkout@v1

    - name: git pull
      run: |
        git clone https://x-access-token:${ACCESS_TOKEN}@github.com/${GITHUB_USERNAME}/${GITHUB_USERNAME}.github.io.git
        git config --global user.email "chousei@github.io"
        git config --global user.name "chousei"

    - name: build
      env:
        API_URL:  ${{ secrets.API_URL }}
        AUTH_API_URL:  ${{ secrets.AUTH_API_URL }}
      run: |
        sed -i "s|http:\/\/API_URL|${API_URL}|" quasar.conf.js
        sed -i "s|http:\/\/AUTH_API_URL|${AUTH_API_URL}|" quasar.conf.js
        docker build -t chousei-front .
        docker run --name chousei-front -d chousei-front

    - name: deploy
      run: |
        docker cp chousei-front:/usr/share/nginx/html/. ./${GITHUB_USERNAME}.github.io
        cd ${GITHUB_USERNAME}.github.io
        git add .
        git commit -m "Deploy $GITHUB_SHA by GitHub Actions"
        git push https://x-access-token:${ACCESS_TOKEN}@github.com/${GITHUB_USERNAME}/${GITHUB_USERNAME}.github.io.git master

    - name: failure
      if: failure()
      run: |
        echo '{"text": "## log  \n<https://github.com/Taita-ldt/chousei/actions/runs/${{ github.run_id }}>", "title": "フロントデプロイ失敗(${{ github.event.head_commit.message }})"}' |
        curl -H 'Content-Type: application/json' -d @- ${{ secrets.TEAMS_URL }}

    - name: success
      run: |
        echo '{"text": "## app  \n<https://btctc-coordinate.github.io/#/>  \n## log  \n<https://github.com/Taita-ldt/chousei/actions/runs/${{ github.run_id }}>", "title": "フロントデプロイ成功(${{ github.event.head_commit.message }})"}' |
        curl -H 'Content-Type: application/json' -d @- ${{ secrets.TEAMS_URL }}