name: Build and Push
 
on:
  push:
    tags:
      - v*
 
jobs:
  build-and-push:
 
    runs-on: ubuntu-latest
    timeout-minutes: 300
 
    steps:
    - uses: actions/checkout@v1    
 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
 
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_FRONT: ${{ secrets.AWS_ECR_REPO_NAME_FRONT }}
        ECR_REPOSITORY_API: ${{ secrets.AWS_ECR_REPO_NAME_API }}
        ECR_REPOSITORY_DB: ${{ secrets.AWS_ECR_REPO_NAME_DB }}
      run: |
        IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
        docker-compose build
        docker tag chousei-front $ECR_REGISTRY/$ECR_REPOSITORY_FRONT:$IMAGE_TAG
        docker tag chousei-api $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_TAG
        docker tag mysql:8 $ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONT:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG