name: Heroku Prevent Sleep
 
on:
  schedule:
    - cron:  '*/25 * 1-10 * *'
    - cron:  '*/25 15-23 28-31 * *'
 
jobs:
  main:
 
    runs-on: ubuntu-latest
    timeout-minutes: 600
 
    steps:
    - uses: actions/checkout@v1    
    - name: Heroku Access
      env:
        API_URL:  ${{ secrets.API_URL }}
      run: |
        curl -H 'Content-type: application/json' ${API_URL}/mng/user

    - name: failure
      if: failure()
      run: |
        echo '{"text": "API動いてないかも、、、、"}' |
        curl -H 'Content-Type: application/json' -d @- ${{ secrets.TEAMS_URL }}
