name: Heroku Prevent Sleep
 
on:
  push:
    tags:
      - heroku*
 
jobs:
  main:
 
    runs-on: ubuntu-latest
    timeout-minutes: 600
 
    steps:
    - uses: actions/checkout@v1    
    - name: Heroku Access
      env:
        API_URL:  ${{ secrets.API_URL }}
      run: |
        curl -H 'Content-type: application/json' ${API_URL}/mng/user

    - name: failure
      if: failure()
      run: |
        echo '{"text": "API動いてないかも、、、、"}' |
        curl -H 'Content-Type: application/json' -d @- ${{ secrets.TEAMS_URL }}
