name: Build
 
on:
  push:
    branches:
      - develop
 
jobs:
  build:
 
    runs-on: ubuntu-latest
    timeout-minutes: 300
 
    steps:
    - uses: actions/checkout@v1    
 
    - name: Build
      run: 
        docker-compose build

    - name: Build failure
      if: failure()
      uses: pullreminders/slack-action@master
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        # "channel"にSlackチャンネルIDを代入
        args: '{\"channel\":\"C010ZGUAGG5\", \"text\":\":sleeping_accommodation:ビルド失敗:sleeping_accommodation:\nhttps://github.com/Taita-ldt/chousei/actions/runs/${{ github.run_id }}\"}'

    - name: Build success
      uses: pullreminders/slack-action@master
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        # "channel"にSlackチャンネルIDを代入
        args: '{\"channel\":\"C010ZGUAGG5\", \"text\":\":person_doing_cartwheel:ビルド成功:person_doing_cartwheel:\nhttps://github.com/Taita-ldt/chousei/actions/runs/${{ github.run_id }}\"}'